version: '3.2'

services:
  portainer:
    image: portainer/portainer-ce
    ports:
      - "8005:8001"
      - "9443:9443"
    restart: always
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  portainer_data:

